### ISSUE TITLE
No code available in example_dino.py and some other files.

### ISSUE THREAD

**Issue by saifhassan** [IPMI-ICNS-UKE/sparsam#1]
Hello, @dericdesta @dschetel @renewerner @ThiloICNS @Moxnie 
Nice work in self-supervised area. 
Please update respository as example_dino and other some files are empty.

**Comment by Moxnie** [comment]
Thanks for the reminder, we updated the example.py with a basic use case, we will further add a more complex one in the future and add more documentation. I did not find any other empyt file though, could you please specify which one you meant?

**Comment by saifhassan** [comment]
> Thanks for the reminder, we updated the example.py with a basic use case, we will further add a more complex one in the future and add more documentation. I did not find any other empyt file though, could you please specify which one you meant?

that was the one empty file, other files are ok, it was internet loading issues. Thanks
