### ISSUE TITLE
Cannot download pretrained models from Git LFS

### ISSUE THREAD

**Issue by laltin** [IPMI-ICNS-UKE/sparsam#4]
Hi,

I cannot download pretrained models due to quota issue on Git LFS. Here is the error message: 
`This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.`

Could you please fix it or host pretrained data anywhere else for me to download?

Thanks.

**Comment by Moxnie** [comment]
Thank you for the remark, models are now available through zenodo. We also updated the readme.
